#!/usr/bin/env python3

import sys
from pathlib import Path


sys.path.insert(
    0,
    str(Path(__file__).resolve().parent / "src"),
)

from redumper_cdda.cli import run


if __name__ == "__main__":
    run()
